### ISSUE TITLE
Get underlaying SPARQL-Queries?

### ISSUE THREAD

**Issue by lugy2001** [MakoLab/RomanticWeb#55]
Is it possible to get the underlaying SPARQL-Queries of LINQ-Queries?

I need that feature for serialization.

And is there a possiblity to do queries in RomanticWeb with SPARQL?

I tried to serialize/deserialize the LINQ-Queries, but that doesn't work at all with subqueries.

**Comment by tpluscode** [comment]
It's not currently possible but the change wouldn't be great.

Could you explain in deatails why you need this? What kind of serialization do you have in mind?

As far as direct SPARQL queries, they aren't possible. Free-form queries will not be possible, because the generated queries must return a fixed set of variables. A SPARQL-like API could theoretically be possible but I fear i would be quite verbose for complex queries. What kind of requirements do you have?

**Comment by lugy2001** [comment]
I have a client-server-architecture where the client requests entities from the server. Both components have the same ontology and share a library with the mapped interfaces. Because of bandwidth limitations I don't want to send every entity (of a type) back to the client. That's where I need to send queries to the server to select the right entities.

My first attempt was to serialize where-expressions (using https://github.com/esskar/Serialize.Linq) , but that doesn't work because of dynamic generated classes (ActLike_...).

**Comment by alien-mcl** [comment]
I've made an update yesterday with few thing, but I've also included a method, with which you can retrieve the underlying store query (by default it would be a SPARQL).
It's not yet on Nuget, but you can grab the build here:
http://ci.t-code.pl/repository/download/bt12/1654:id/RomanticWeb/RomanticWeb.0.3.123.0.nupkg

All you have to do is to cast your LINQ query to it's underlying provider, EntityQueryable<> and call a ToTraceString() method
