### ISSUE TITLE
Unable to get data using entity context without meta graph

### ISSUE THREAD

**Issue by wk-pl** [MakoLab/RomanticWeb#60]
Hi,

Is it possible to use RomanticWeb's EntityContext to retrieve data from a triple store which doesn't include the meta graph's triples? For example, I tried loading some triples by adding them to the triple store from URI - it added a bunch of triples to the store, but after creating the entityContext using the triple store - I couldn't get any results:

```
   var tripleStore = new TripleStore();
   tripleStore.AddFromUri(new Uri(...));

   var entityContext = EntityContextFactory.FromConfiguration("config")
                                  .WithMetaGraphUri(new Uri("http://example.com/data/"))
                                  .WithDotNetRdf(tripleStore);

   var results = entityContext.AsQueryable();
```

The above results are empty, even if the underlying triple store has some triples. I guess it can't get any data because the given meta graph uri is not connected to the triples added to the store from an URI.

Is it possible, however, to make it work nonetheless?

Another example, where I would like to have it working is when I try to create a dictionary (for example a dictionary of labels to make it simple) from an existing ontology. Imagine we have an ontology which has some dictionary data in the form of: 
```
<http://someUri/KeyValue> rdfs:type SomeClass ;
                          rdfs:label "Some value"^^xsd:string .
```
I would need to load the triples from the ontology, read the necessary triples and create a c# Dictionary<Uri, string> containing mapped URI's to their labels for later use. Is this accomplishable using RomanticWeb? Or maybe there is an other way of reading such data from ontologies I just couldn'y find?

**Comment by alien-mcl** [comment]
Unfortunately, meta graph is the only thing required in order for RomanticWeb to work properly. This would be due to a couple of reasons, i.e.:

* prevent loading vast number of triples possibly involved
* avoid querying for blank nodes i.e. for RDF lists

It is mandatory to have a statement in that meta-graph that binds a resource with it's containing graph allowing RM to load only that part of the triple store.

While it's mandatory, it is possible to provide a custom implementation that selects a graph for a given resource allowing you to have i.e. graph containing whole ontology - it is how I loaded OWL files into an in-memory triple store.

I was thinking on pissibilities to have an alternative implementation that would make this requirement obsolete (i.e. to work with SPARQL endpoints which won't have that meta graph), but nothing abvious so far came up my mind.
